src/AppBundle/Entity/TagList.php
<?php
/**
 * Created by PhpStorm.
 * User: muszkin
 * Date: 24.05.17
 * Time: 12:16
 */

namespace AppBundle\Entity;

use AppBundle\Model\BaseModel;
use Doctrine\ORM\Mapping as ORM;
use AppBundle\Model\TagListInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * Class TagList
 * @package AppBundle\Entity
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TagListRepository")
 * @ORM\Table(name="tag_list")
 */
class TagList extends BaseModel implements TagListInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(name="tag_list_id",type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @ORM\Column(name="date",type="datetime")
     */
    protected $date;

    /**
     * @ORM\Column(name="ticket_id",type="integer",nullable=true)
     */
    protected $ticket_id;

    /**
     * @ORM\Column(name="connection_id",type="string",nullable=true)
     */
    protected $connection_id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Tag",inversedBy="tag_list")
     * @ORM\JoinColumn(name="tag_id",referencedColumnName="tag_id")
     */
    protected $tag;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Agent",inversedBy="tags_list")
     * @ORM\JoinColumn(name="agent_id",referencedColumnName="agent_id")
     */
    protected $agent;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Team",inversedBy="tags_list")
     * @ORM\JoinColumn(name="team_id",referencedColumnName="team_id")
     */
    protected $team;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Source",inversedBy="tags_list")
     * @ORM\JoinColumn(name="source_id",referencedColumnName="source_id")
     */
    protected $source;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Category",inversedBy="tags_list")
     * @ORM\JoinColumn(name="category_id",referencedColumnName="category_id")
     */
    protected $category;

    protected $count;

    public function __toString()
    {
        $date = $this->getDate();
        return json_encode([
            "id" => $this->getId(),
            "date" => $date->format('Y-m-d H:i:s'),
            "agent" => $this->getAgent()->getName(),
            "source" => $this->getSource()->getName(),
            "category" => $this->getCategory()->getName(),
            "tag" => $this->getTag()->getName(),
            "team" => $this->getTeam()->getName()
        ]);
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set date
     *
     * @param \DateTime $date
     *
     * @return TagList
     */
    public function setDate($date)
    {
        $this->date = $date;

        return $this;
    }

    /**
     * Get date
     *
     * @return \DateTime
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * Set tag
     *
     * @param \AppBundle\Entity\Tag $tag
     *
     * @return TagList
     */
    public function setTag(\AppBundle\Entity\Tag $tag = null)
    {
        $this->tag = $tag;

        return $this;
    }

    /**
     * Get tag
     *
     * @return \AppBundle\Entity\Tag
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Set agent
     *
     * @param \AppBundle\Entity\Agent $agent
     *
     * @return TagList
     */
    public function setAgent(\AppBundle\Entity\Agent $agent = null)
    {
        $this->agent = $agent;

        return $this;
    }

    /**
     * Get agent
     *
     * @return \AppBundle\Entity\Agent
     */
    public function getAgent()
    {
        return $this->agent;
    }

    /**
     * Set team
     *
     * @param \AppBundle\Entity\Team $team
     *
     * @return TagList
     */
    public function setTeam(\AppBundle\Entity\Team $team = null)
    {
        $this->team = $team;

        return $this;
    }

    /**
     * Get team
     *
     * @return \AppBundle\Entity\Team
     */
    public function getTeam()
    {
        return $this->team;
    }

    /**
     * Set source
     *
     * @param \AppBundle\Entity\Source $source
     *
     * @return TagList
     */
    public function setSource(\AppBundle\Entity\Source $source = null)
    {
        $this->source = $source;

        return $this;
    }

    /**
     * Get source
     *
     * @return \AppBundle\Entity\Source
     */
    public function getSource()
    {
        return $this->source;
    }

    /**
     * Set category
     *
     * @param \AppBundle\Entity\Category $category
     *
     * @return TagList
     */
    public function setCategory(\AppBundle\Entity\Category $category = null)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return \AppBundle\Entity\Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @return mixed
     */
    public function getTicketId()
    {
        return $this->ticket_id;
    }

    /**
     * @param mixed $ticket_id
     */
    public function setTicketId($ticket_id)
    {
        $this->ticket_id = $ticket_id;
    }

    /**
     * @return mixed
     */
    public function getConnectionId()
    {
        return $this->connection_id;
    }

    /**
     * @param mixed $connection_id
     */
    public function setConnectionId($connection_id)
    {
        $this->connection_id = $connection_id;
    }

    /**
     * @return mixed
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     * @param mixed $count
     */
    public function setCount($count)
    {
        $this->count = $count;
    }
}

src/AppBundle/Resources/views/Main/agents.twig
    {% trans_default_domain "tag" %}
    <option value>{{ "All.agents"|trans }}</option>
{% for agent in agents %}
    <option value="{{ agent.id }}">{{ agent }}</option>
{% endfor %}

src/AppBundle/Resources/views/Main/index.html.twig
{% trans_default_domain "tag" %}
{% extends '@App/base.html.twig' %}
{% block content %}
    {% if tags is empty %}
        <div class="row">
            <div class="col-xs-12" id="no-tags">
                {{ "no.tags.filter" |trans }}
            </div>
        </div>
    {% else %}
        <div class="charts">
        {% for key,chart in charts %}
            <div class="row">
                <div class="col-xs-12">
                    <div class="charts-pie charts-pie-{{ key }}" data-json="{{ chart.pie|json_encode }}" id="charts-pie-{{ key }}" data-name="{{ chart.name }}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12">
                    <div class="charts-line charts-line-{{ key }}" data-json="{{ chart.line|json_encode }}" id="charts-line-{{ key }}" data-name="{{ chart.name }}" data-graphs="{{ chart.graphs|json_encode }}">
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
        <div class="row">
            <div class="col-xs-12">
                <div id="charts-table">
                    <table class="table table-responsive table-bordered" id="tags-table">
                        <thead>
                            <tr>
                                <th>{{ "Id"|trans }}</th>
                                <th>{{ "Date"|trans }}</th>
                                <th>{{ "Tag"|trans }}</th>
                                <th>{{ "Agent"|trans }}</th>
                                <th>{{ "Team" |trans}}</th>
                                <th>{{ "Source" |trans}}</th>
                                <th>{{ "Category"|trans }}</th>
                                <th>{{ "Ticket id or Connection id"|trans }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for tag in tags %}
                                <tr>
                                    <td>{{ tag.id }}</td>
                                    <td>{{ tag.date|date('Y-m-d H:i:s') }}</td>
                                    <td>{{ tag.tag | trans}}</td>
                                    <td>{{ tag.agent | trans}}</td>
                                    <td>{{ tag.team | trans}}</td>
                                    <td>{{ tag.source | trans}}</td>
                                    <td>{{ tag.category | trans}}</td>
                                    {% if tag.ticketId is not null %}<td><a href="https://pomoc.shoper.pl/staff/index.php?/Tickets/Ticket/View/{{ tag.ticketId }}" target="_blank">{{ tag.ticketId }}</a></td>{% endif %}
                                    {% if tag.connectionId is not null %}<td>{{ tag.connectionId }}</td>{% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    {% endif %}
    {% include '@App/Main/scripts.html.twig' %}
{% endblock %}

src/AppBundle/Resources/views/Main/scripts.html.twig
{% trans_default_domain "tag" %}
{% block scripts %}
    <script type="text/javascript">
        var trans = "{{ app.request.locale }}";

        function setDateTimePicker(){
            $('#menu_from').datepicker({
                dateFormat:'yy-mm-dd'
            });
            $('#menu_to').datepicker({
                dateFormat:'yy-mm-dd'
            });
        }

        function getAgents(team){
            var url = "/" + trans + "/getAgents";
            $.ajax({
                url: url,
                data:{
                    team: team
                },
                success:function(data){
                    $('#menu_agent').html(data);
                    $('#menu_agent').selectpicker('refresh');
                }
            });
        }

        function getTags(category){
            var url = "/" + trans + "/getTags";
            $.ajax({
                url: url,
                data:{
                    category:category
                },
                success:function(data){
                    $('#menu_tag').html(data);
                    $('#menu_tag').selectpicker('refresh');
                }
            })
        }

        function resetTags(){
            $('#menu_tag').html(originalTags);
            $('#menu_tag').selectpicker('refresh');
        }

        function resetAgents(){
            $('#menu_agent').html(originalAgents);
            $('#menu_agent').selectpicker('refresh');
        }

        function initSelectBox(){
            var options = {
                deselectAllText: "{{ "deselect.all"|trans }}",
                selectAllText: "{{ "select.all"|trans }}"
            };
            $('#menu_tag').selectpicker(options);
            $('#menu_agent').selectpicker(options);
            $('#menu_team').selectpicker(options);
            $('#menu_source').selectpicker(options);
            $('#menu_group').selectpicker(options);
            $('#menu_category').selectpicker(options);
        }

        function initTable(){
            $('#tags-table').dataTable({
                order:[1,'asc'],
                language:{
                    decimal:        "{{ "decimal"|trans }}",
                    emptyTable:     "{{ "emptyTable"|trans }}",
                    info:           "{{ "info"|trans }}",
                    infoEmpty:      "{{ "infoEmpty"|trans }}",
                    infoFiltered:   "{{ "infoFiltered"|trans }}",
                    infoPostFix:    "{{ "infoPostFix"|trans }}",
                    thousands:      "{{ "thousands"|trans }}",
                    lengthMenu:     "{{ "lengthMenu"|trans }}",
                    loadingRecords: "{{ "loadingRecords"|trans }}",
                    processing:     "{{ "processing"|trans }}",
                    search:         "{{ "search"|trans }}",
                    zeroRecords:    "{{ "zeroRecords"|trans }}",
                    paginate: {
                        first:      "{{ "first"|trans }}",
                        last:       "{{ "last"|trans }}",
                        next:       "{{ "next"|trans }}",
                        previous:   "{{ "previous"|trans }}"
                    },
                    aria: {
                        sortAscending:  "{{ "sortAscending"|trans }}",
                        sortDescending: "{{ "sortDescending"|trans }}"
                    }
                }
            });
        }

        var locale = {
            "team": "{{ "Team"|trans }}",
            "agent": "{{ "Agent"|trans }}",
            "category": "{{ "Category"|trans }}",
            "source": "{{ "Source"|trans }}",
            "tag": "{{ "Tag"|trans }}"
        };

        function createChart(){
            var pieSelector = ".charts-pie";
            $(pieSelector).each(function(key,index) {
                var lastClassPie = $(index).attr('class').split(' ').pop();
                var chartDataPie = $(index).data('json');
                var dataPie = [];
                $.each(chartDataPie, function (key, value) {
                    dataPie.push(value);
                });
                AmCharts.makeChart(lastClassPie,
                    {
                        "type": "pie",
                        "balloonText": "[[title]]<br><span style='font-size:14px'><b>[[value]]</b> ([[percents]]%)</span>",
                        "labelText": "[[title]]: [[value]] ([[percents]]%)",
                        "titleField": "category",
                        "valueField": "value",
                        "allLabels": [],
                        "balloon": {},
                        "legend": {
                            "enabled": true,
                            "align": "center",
                            "markerType": "circle"
                        },
                        "titles": [
                            {
                                "id": "category",
                                "text": "{{ "Total tags (filter: "|trans }}" + locale[$(index).data('name')] + ")"
                            }
                        ],
                        "export": {
                            "enabled":true
                        },
                        "dataProvider": dataPie
                    }
                );
            });
            var lineSelector = ".charts-line";
            $(lineSelector).each(function(key,index){
                var lastClassLine = $(index).attr('class').split(' ').pop();
                var chartDataLine =  $(index).data('json');
                var graphsDataLine = $(index).data('graphs');
                var dataLine = [];
                var graphs = [];
                var period = chartDataLine.period;
                delete chartDataLine.period;
                $.each(chartDataLine,function(k1,date){
                    var record = {};
                    if ('WW' === period){
                        var d = k1.split(" ");
                        record.date = moment().day("Monday").year(d[0]).week(d[1]).toDate();
                    }else {
                        record.date = k1;
                    }
                    $.each(date,function(k2,team){
                        record[k2] = team;
                    });
                    dataLine.push(record);
                });
                $.each(graphsDataLine,function(k2,ele){
                    var graph = {};
                    graph.id = ele;
                    graph.title = ele;
                    graph.valueField = ele;
                    graph.bullet = "round";
                    graphs.push(graph);
                });
                AmCharts.makeChart(lastClassLine,
                    {
                        "type": "serial",
                        "categoryField": "date",
                        "dataDateFormat": "YYYY-MM-DD JJ:NN:SS",
                        "categoryAxis": {
                            "parseDates": true,
                            "dateFormats": [{
                                period: 'DD',
                                format: 'MMM DD'
                            }, {
                                period: 'WW',
                                format: 'MMM DD'
                            }, {
                                period: 'MM',
                                format: 'MMM'
                            }, {
                                period: 'YYYY',
                                format: 'YYYY'
                            }],
                            "minPeriod": period
                        },
                        "chartCursor": {
                            "enabled": true
                        },
                        "chartScrollbar": {
                            "enabled": true
                        },
                        "trendLines": [],
                        "graphs": graphs,
                        "guides": [],
                        "valueAxes": [
                            {
                                "id": "ValueAxis-1",
                                "title": "{{ "Tags Amount" |trans}}"
                            }
                        ],
                        "allLabels": [],
                        "balloon": {},
                        "legend": {
                            "enabled": true,
                            "useGraphSettings": true
                        },
                        "export": {
                            "enabled":true
                        },
                        "titles": [
                            {
                                "id": "title2",
                                "size": 15,
                                "text": locale[$(index).data('name')] + " [{{ "time"|trans }}]"
                            }
                        ],
                        "dataProvider": dataLine
                    }
                );
            });
        }

        var originalAgents,originalTags;

        String.prototype.capitalize = function() {
            return this.charAt(0).toUpperCase() + this.slice(1);
        };

        $(document).ready(function(){
            setDateTimePicker();
            initSelectBox();
            originalTags = $('#menu_tag').html();
            originalAgents = $('#menu_agent').html();
            $('#menu_category').on('change',function(){
                if (this.value != ''){
                    getTags(this.value);
                }else{
                    resetTags();
                }
            });
            $('#menu_team').on('change',function(){
                if (this.value != ''){
                    getAgents(this.value);
                }else{
                    resetAgents();
                }
            });
            if ($('#no-tags') != undefined){
                initTable();
                createChart();
            }
        });
    </script>
{% endblock scripts %}

src/AppBundle/Resources/views/Main/tags.twig
{% trans_default_domain "tag" %}
    <option value>{{ "All"|trans }}</option>
{% for tag in tags %}
    <option value="{{ tag.id }}">{{ tag|trans }}</option>
{% endfor %}